docker:
  users:
    - cmdi
  name: docker-ce
  repo: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  script_file: /tmp/install_docker.sh
  registry_mirrors: https://k73774q1.mirror.aliyuncs.com

pip:
  index_url: http://pypi.douban.com/simple
  trusted_host: pypi.douban.com


log_file: /var/log/docker_install.log
